services:
  db:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_DB: ticketdb
      POSTGRES_USER: ticketuser
      POSTGRES_PASSWORD: ticketpass
      # Aggiunto Timezone per allineare il database
      TZ: Europe/Rome
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: ticketblock-backend
    depends_on:
      db:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ticketdb
      SPRING_DATASOURCE_USERNAME: ticketuser
      SPRING_DATASOURCE_PASSWORD: ticketpass
      GANACHE_URL: http://host.docker.internal:7545
      # 1. Imposta il fuso orario a livello OS del container
      TZ: Europe/Rome
      # 2. Forza Java a usare l'orario italiano (fondamentale per i filtri data)
      JAVA_TOOL_OPTIONS: "-Duser.timezone=Europe/Rome"
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: ticketblock-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  postgres_data: