spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketblock
    username: team
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# Log su file e livello di log per com.ticketblock
logging:
  file:
    name: backend/logs/ticketblock.log
  level:
    com:
      ticketblock: DEBUG





